Data Catalogue
earthwave/glambie pull request #6
Opened 2022-07-26 17:53 UTC by liviajakob

Changes to include a data catalogue class that reads the metadata json file. and stores all datasets.

2022-07-27 16:41 UTC, alex-ew commented on glambie/const/data_groups.py
> +class GlambieDataGroups():
So far this reads like read-only dictionary. If it doesn't need to be read-only, then just inherit from dict. If it does you can follow one of these examples: https://stackoverflow.com/questions/19022868/how-to-make-dictionary-read-only

But you get all the item look up stuff (and set uniqueness) for free if your dictionary is:
{ "name": GlambieDataGroup}

2022-07-27 16:44 UTC, alex-ew commented on glambie/const/regions.py
> +        string = ''
Minor one. I think this is a one liner with '\n'.join(cls.regions).
or with list comprehension if you need to force type '\n'.join([str(region) for region in cls.regions]).

2022-07-27 16:45 UTC, alex-ew commented on glambie/data/data_catalogue.py
> +            print(type(meta_data))
Should be logged or removed

2022-07-27 16:46 UTC, alex-ew commented on glambie/data/data_catalogue.py
> +    def get_regions(self) -> list:
The type hint is cool, but it's nicer to see what you'll get a list of. i.e. List[str] etc

2022-07-27 16:51 UTC, alex-ew commented on glambie/const/data_groups.py
> +class GlambieDataGroups():
Think the last comment was lost..(?)

This looks like a readonly dictionary. It probably doesn't need to be readonly, in which case just inherit from dict. If it does need to be readonly, you could follow something like this: 
https://stackoverflow.com/questions/19022868/how-to-make-dictionary-read-only

If you inherit from dict you get this lookup stuff for free

2022-07-27 16:52 UTC, alex-ew commented on glambie/const/data_groups.py
> +        return GlambieDataGroups.get_data_group_by_name(name)
If it's a simple duplicate of the below method, just keep one of them?

2022-07-27 16:52 UTC, alex-ew commented on glambie/const/data_groups.py
> +        return GlambieDataGroups.get_data_group_by_name(name)
But both disappear with the dict inheritance

2022-07-27 16:53 UTC, alex-ew reviewed
Generally looking good - like the tests. I still need to work through some of the files - will pick up in the morning

2022-07-28 08:18 UTC, alex-ew commented on glambie/data/timeseries_data.py
> +    def __init__(self, data_group: Optional[GlambieDataGroup] = None, region: Optional[RGIRegion] = None,
We could reuse the dataclass approach here. I had to play with it myself but for optional values you just use something like 
```
from dataclasses import dataclass


@dataclass
class ClassWithDefaults():
    mask: str
    msg: str = None

    def test(self):
        return(self.msg)


cls = ClassWithDefaults(mask="str")

print(cls.mask, cls.msg, cls.test())
```

2022-07-28 08:24 UTC, alex-ew commented on glambie/data/timeseries_data.py
> +    def read_data(self, data_filepath: Optional[str] = None):
Let's have a chat about this pattern in general. I feel like there's a cleaner way to capture what you're trying to achieve. For my own benefit later: The class has some basic info and then some more information that's populated with ingest_data. But you want the contents to lazy load. It's probably better to have a class state flag self.is_ingesed. And then whenever you need the data have a method ingest_if_necessary() that checks if it's already ingested or not and loads it. Maybe - let's discuss :-)

2022-07-28 08:32 UTC, alex-ew commented on glambie/data/timeseries_data.py
>          return float(resolution)
Should it be a @property like the other dataset info above?

2022-07-28 10:05 UTC, liviajakob commented on glambie/data/data_catalogue.py
> +            print(type(meta_data))
oops that slipped in

2022-07-29 07:46 UTC, alex-ew requested changes
Nice - things are looking a lot simpler now and the general object hierarchy is clearer. The test coverage is great - it could pass operational standards with a few cosmetic changes. I think we just need a couple more docstrings on key methods and we're done

2022-07-29 07:46 UTC, alex-ew commented on glambie/data/timeseries.py
> +    def __init__(self, region: RGIRegion = None, data_group: GlambieDataGroup = None, data_filepath: str = None,
A comment in the constructor would be good about the lazy data loading or presence of data as input

2022-07-29 07:46 UTC, alex-ew commented on glambie/data/data_catalogue.py
> +    def get_filtered_catalogue(self, region_name: str = None, data_group: str = None,
I think this method in particular would especially benefit from a return type hint and doc strings so it's clear the user gets a new catalogue object back

2022-07-29 10:11 UTC, alex-ew approved these changes
Looking good

2022-07-29 10:12 UTC, merged