Calculate and save results in gigatonnes
earthwave/glambie pull request #64
Opened 2023-08-07 18:01 UTC by liviajakob

Simple changes to convert and save out the results within the glambie processing algorithm to gigatonnes.

Done on regional as well as global level, using existing conversion functions

2023-08-07 22:06 UTC, alex-ew requested changes
Mostly seems straight forward. The biggest issue is the duplicated function that, unless I've missed something, would be trivial to extend an existing function to handle. It would be better to some rudimentary test coverage of the added features, too.

2023-08-07 22:06 UTC, alex-ew commented on tests/processing/test_process_global_results.py
> +from glambie.processing.process_global_results import _combine_regional_results_in_mwe_into_global
No tests for new functions. The new functions should have at least some cursory coverage.

2023-08-08 10:22 UTC, liviajakob commented on glambie/processing/process_regional_results.py
> +    combined_region_timeseries_gt = combined_region_timeseries.apply_area_change(apply_change=False)
No it's for applying or removing the area change. I have now renamed and I think its more clear now?

Now:
apply_or_remove_area_change(apply_area_change=False)

2023-08-08 11:31 UTC, liviajakob commented on glambie/processing/process_global_results.py
> +def _combine_regional_results_in_gt_into_global(regional_results_catalogue: DataCatalogue) -> Timeseries:
Yes, that was lazy! It's one function now!

2023-08-08 11:35 UTC, liviajakob commented on glambie/processing/main.py
> +    # catalogue_data_group_results_per_region = DataCatalogue.from_list(
done

2023-08-08 11:41 UTC, liviajakob commented
Thanks for feedback. That's it done :)
Main change is that I combined global aggregation into 1 function and added a unit test for gigatonnes.

2023-08-08 23:34 UTC, alex-ew commented on glambie/processing/process_regional_results.py
> +    combined_region_timeseries_gt = combined_region_timeseries.apply_area_change(apply_change=False)
I see. This is definitely clearer and I can see why you wouldn't want to duplicate the logic in the function.

I think part of this comes down to the fact "area_change" itself isn't immediately clear to me. adjust_area_assuming_linear_trend"? I was going to suggest something like the following but I'm not convinced it's any clearer.. Anyway, I'll leave for now

class TimeSeries:

    def apply_area_change(self, rgi_area_version: int = 6):
        return self._apply_or_remove_area_change(rgi_area_version=rgi_area_version, apply_area_change=True)

    def remove_area_change(self, rgi_area_version: int = 6):
        return self._apply_or_remove_area_change(rgi_area_version=rgi_area_version, apply_area_change=False)

    def _apply_or_remove_area_change(self, rgi_area_version: int = 6, apply_area_change: bool = True):

2023-08-08 23:38 UTC, alex-ew commented on glambie/processing/process_global_results.py
> +def _combine_regional_results_in_gt_into_global(regional_results_catalogue: DataCatalogue) -> Timeseries:
This is much cleaner. Thanks

2023-08-08 23:41 UTC, alex-ew approved these changes
The changes look cleaner - especially de-duplicating the combine regional results one

2023-08-08 23:41 UTC, merged